### ISSUE TITLE
Il2Cpp.Thread::schedule error

### ISSUE THREAD

**Issue by commonuserlol** [vfsfitvnm/frida-il2cpp-bridge#276]
hello, i need the function to be executed in another thread (asynchronously), otherwise the game will freeze for 1-2 seconds.
`Il2Cpp.Thread::schedule` throws an error `il2cpp: couldn't find GetDisplayName in Runtime, did you mean .cctor?`
my code:
```
Il2Cpp.perform(() => {
        const AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
        AssemblyCSharp.class("Axlebolt.Standoff.Game.GameController").method("AGAADFEAHGCGFBH").implementation = function (event: Il2Cpp.Object, player: Il2Cpp.Object) {
            this.method("AGAADFEAHGCGFBH").invoke(event, player);
            Il2Cpp.currentThread?.schedule(() => {
                console.log("hello");
            }, 1000);
        }
    });
```
unity version: `2021.3.16f1`
android: 12.1

**Comment by vfsfitvnm** [comment]
Thanks for reporting! 
In order to being able to schedule a callback into another thread, I need to choose a simple (static, no parameters) , unused-ish method to use as trampoline.
I designated `Mono.Runtime::GetDisplayName` as such; however that game is also using Mono now (?), and it looks like that class is different. So, I'm just fallbacking to `.cctor` in case `GetDisplayName` isn't available.

**Comment by Rishabhg71** [comment]
@vfsfitvnm How exactly can we move a method onto another thread?

Btw love this library ❤️

UPDATE: Nevermind, I was able to create a new thread. However, my game still freezes when I try to invoke any control-related methods, even when using a separate thread (feel free to share any tips if you have them).

For anyone facing a similar issue, you can use setTimeout to run a function on a different thread.

```ts
setImmediate(() => {
    console.log(Il2Cpp.currentThread?.id, Il2Cpp.mainThread.id);
})
```
