### ISSUE TITLE
abort was called when trying to invoke method

### ISSUE THREAD

**Issue by simind** [vfsfitvnm/frida-il2cpp-bridge#3]
I have a C# MonoBehaviour class "HelloWorld.cs" and a frida "index.ts".
When I try to invoke a method named "ChangeValue", an error shows as follow.

I think maybe it's because the javascript variable "instance" gets garbage-collected.
But I am not sure.

**If so, is it possible to keep alive an instance from an Interceptor so I can use it later outside "onEnter" function?**

```
Error: abort was called
    at _invoke (/index.js:2645)
    at invoke (/index.js:2632)
    at <anonymous> (/index.js:36)
    at apply (native)
    at <anonymous> (frida/runtime/core.js:53)
```

```cs
// HelloWorld.cs 
using UnityEngine;
using TMPro;

public class HelloWorld : MonoBehaviour
{
    public TextMeshProUGUI text;

    public void OnBtnChangeValue() {
        ChangeValue();
    }

    public void ChangeValue () {
        text.text = Random.Range(1, 10000).ToString();
    }
}
```
```ts
// index.ts
async function main() {
    await Il2Cpp.initialize();

    // Uncomment for REPL access
    (global as any).Il2Cpp = Il2Cpp;

    // define a global variable
    let globalInstance: Il2Cpp.Object | null;

    const HelloWorldClass = Il2Cpp.domain.assemblies['Assembly-CSharp'].image.classes['HelloWorld'];
    HelloWorldClass.methods.OnBtnChangeValue.intercept({
        onEnter (instance, parameters) {
            console.log('HelloWorld.OnBtnChangeValue enter...');

            // save as global
            globalInstance = instance;
        }
    });

    let timer = setInterval( () => {
        if (globalInstance) {
            console.log('here...');
            clearInterval(timer);

            // invoke "ChangeValue" by globalInstance
            globalInstance.methods.ChangeValue.invoke();
        }
    }, 2000);
}

main().catch(error => console.log(error.stack));
```

**Comment by vfsfitvnm** [comment]
@simind 
Thank you for filing this issue.

Are you aware of the instance lifetime? Are you sure it isn't garbage collected by C#? You could try `Il2Cpp.GC.disable()` in that case.

Otherwise, if the problem is the javascript variable, you could define `globalInstance` like a real global - it won't GCed by JS:
```ts
declare global {
    let globalInstance: Il2Cpp.Object | null;
}
```

However, I can think of another reason: you are trying to invoke that method from another thread (which usually ends in an access violation error).

By the way, is that snippet just an example? What are you trying to achieve?

**Comment by simind** [comment]
Thank you so much for the quick reply.

I am trying to replace a c# method "Login" from a Unity game class.
When the "Login" method is called, I want to send login request to my own server.
And if login succeed, I want to somehow invoke "OnLoginSuccess" method.

```ts
// LoginScene.cs
// This is a Monobehaviour class from a Unity Game I want to reverse.
using UnityEngine;
using UnityEngine.SceneManagement;
public class LoginScene : MonoBehaviour
{
    void Login () {
        // send asynchronous login request to game server via http
        // when login success, "OnLoginSuccess" will be called
    }

    void OnLoginSuccess () {
        // go to next scene
        SceneManager.LoadScene("MainScene");
    }
}
```

```ts
// index.ts
async function main() {
    await Il2Cpp.initialize();

    // Uncomment for REPL access
    (global as any).Il2Cpp = Il2Cpp;

    const LoginSceneClass = Il2Cpp.domain.assemblies['Assembly-CSharp'].image.classes['LoginScene'];
    LoginSceneClass.methods.Login.implementation = (instance, parameters) => {
        console.log('LoginScene.Login enter...');

        // here, I send login request to "my own server" asynchronously
        http.getAsync('http://xxx', (success: boolean) => {
            if (success) {
                // login success

                // Here is what I want to achieve.
                // Is it possible to invoke the method 'OnLoginSuccess' from Unity class 'LoginScene'?
            }
        });

        return undefined;
    };
}
```

**Comment by vfsfitvnm** [comment]
@simind 

Are you getting the abort error when trying to do the following?

```ts
http.getAsync('http://xxx', (success: boolean) => {
    if (success) {
       instance.methods.OnLoginSuccess.invoke(); // <--- Error
    }
});
```

If so, we are probably looking for something similar to frida's `Java.retain`, but I honestly I don't know how implement it (and it wouldn't solve the foreign thread problem).

The quickest solution may be perform the http request synchronously. You could use il2cpp as well, I did it once (I don't remember exactly what I did / which method or classes I used, but you have to perform the request, busy wait it and finally retrieve the result).

Another solution would consist in:
- Save the instance somewhere, like you did in the previous script (make sure it isn't garbage collected)
- Perform the async http request
- On success, attach an interceptor to any frequently invoked functions (like a rendering one), this will ensure the code will be executed on the correct thread
- "Resume" the instance and invoke the target method.

By the way, you should check what the problem really is:
- `instance` gets garbage collected by il2cpp gc
- `instance` gets garbage collected by js gc
- `OnLoginSuccess` is invoked from the wrong thread

You probably want to use `Il2Cpp.GC.choose` to verify what's the problem is: if it finds the instance, then it wasn't garbage collected by il2cpp gc

**Comment by simind** [comment]
Yes, I am looking for something similar to frida's Java.retain.
Thank you for the solutions. That really helps a lot.
I will do more test to figure out what the problem really is.

**Comment by vfsfitvnm** [comment]
@simind 
Hi! Probably some of [these api](https://github.com/djkaty/Il2CppInspector/blob/master/Il2CppInspector.Common/Cpp/Il2CppAPIHeaders/2019.1.0-2019.2.21.h#L131) will be useful.

Would you tell me the application name you were working on, so I can test them?

**Comment by vfsfitvnm** [comment]
I feel like `Il2Cpp.GCHandle` can address this issue. I couldn't test it because I wasn't able to reproduce your scenario. Please reopen if needed.
