### ISSUE TITLE
[QUESTION] Is it possible to get caller when entering a method?

### ISSUE THREAD

**Issue by TooYoungTooSimp** [vfsfitvnm/frida-il2cpp-bridge#43]
I'm currently trying to get the text displayed in an app.
So I hooked `TextGenerator.PopulateWithErrors`. In this way I can get the text I want but....
When a sentence is "abcdefg", I got 7 separate method onEnter callback:
```
a
ab
abc
abcd
abcde
abcdef
abcdefg
```
The displayed characters are increased one at each time.
So I'm wondering how to get the original string "abcdefg" at once.
I think get the caller of `TextGenerator.PopulateWithErrors` may help.
By the way, I'm wondering how to monitor nested calls in a method. So I can know where these text really from?

**Comment by vfsfitvnm** [comment]
Unfortunately, you can't obtain the caller `Il2CppMethod`. This information is stripped in release builds.
However, there are two solutions.

The first one consists in [tracing](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Snippets#tracing) the classes/methods you suspect are calling `TextGenerator.PopulateWithErrors` (use the `full` or `detailed` tracing). You will be able to see nested method calls.

The second one consists in using a disassembler (I use ghidra). You must analyze the il2cpp library with it first, then you [dump](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Snippets#dumping) the application, and finally you have to [load](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Miscellaneous#dump-parsing) the method names. After that, you can inspect the "call tree" the disassembler populates for you; otherwise you can get a [backtrace](https://frida.re/docs/javascript-api/#thread):
```ts
Interceptor.attach(TextGenerator.methods.PopulateWithErrors.virtualAddress, {
    onEnter() {
        const backtrace = Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join("\n");
        console.log(backtrace + "\n");
    }
});
```

**Comment by TooYoungTooSimp** [comment]
Thank you for your quick and detailed guidance, I will give it a try!

**Comment by vfsfitvnm** [comment]
Reopen or ask on "Discussion" tab if you encounter issues
