### ISSUE TITLE
iOS Tester

### ISSUE THREAD

**Issue by busmanl30** [vfsfitvnm/frida-il2cpp-bridge#44]
Hey, I’m willing to try this for iOS and work with you so this script can be universal, do you have any outside contacts, you can add me on discord busmanl30#3931 thank you

**Comment by vfsfitvnm** [comment]
Hi, thanks for the interest, however ios is already supported (https://github.com/vfsfitvnm/frida-il2cpp-bridge/commit/fbd96e7ec9b364b7d4bb4c1e019b25edaf4ebf58)...

**Comment by busmanl30** [comment]
Just looked at Code an not all games have a unity framework, sometimes it’s just in the built in binary itself

**Comment by busmanl30** [comment]
Also another thing, can this dump a globalmeta from memory?

**Comment by vfsfitvnm** [comment]
> Just looked at Code an not all games have a unity framework, sometimes it’s just in the built in binary itself

I actually check that here:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/base.ts#L60

> Also another thing, can this dump a globalmeta from memory?

No, kind of useless

**Comment by busmanl30** [comment]
Oh because sometimes I prefer having an Ida script ajd with that most of the time when I use il2cppdunoer I can get the static pointers of a class and it would be ClassName__TypeInfo

**Comment by vfsfitvnm** [comment]
Relying on stock typedefs will lead to problems. It's just so easy to modify them (e.g adding or swapping fields), vendors will start doing so more frequently. That's why I had to find alternative ways to retrieve some important data.
I don't want to deal with global-metadata for the same reason. It's too easy to mess it up, even once it's deobfuscated, decrypted, etc.

However, I have a similar thing on my roadmap that will improve static analysis (https://github.com/vfsfitvnm/frida-il2cpp-bridge/commit/7a666dc93b6d85ca45c15b1a761870fd4ade237d).
![Screenshot_20211019_105001](https://user-images.githubusercontent.com/46219656/137876799-658775ca-13bb-4562-8b85-23fefb190810.png)

**Comment by busmanl30** [comment]
I mean it wasn’t what I meant, I use a static pointer so i I don’t need to hook, which in iOS can sometimes be detected so I find a static route and just create a thread, this way it works on non jailbroken devices too since hooking isn’t possible without a jailbreak, I’ll show you what I’m talking about when I’m home

**Comment by vfsfitvnm** [comment]
Closing because of no updates
