### ISSUE TITLE
il2cpp: 10 seconds have passed and libil2cpp.so has not been loaded yet, is the app running?

### ISSUE THREAD

**Issue by Sazxt** [vfsfitvnm/frida-il2cpp-bridge#495]
<img width="960" alt="image" src="https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/51526089/85659575-2006-44ea-b2ba-b102ebcec41d">

why not work x86 ? 

using bluestacks emulator

**Comment by ghost** [comment]
same issue but if I add `--realm=emulated` like `frida -U -f "com.farstar.bsb" -l index.js --realm=emulated`, it crashes

```
Spawned `com.farstar.bsb`. Resuming main thread!
Error: unable to intercept function at 0xc7712b80; please file a bug
    at value (frida/runtime/core.js:367)
    at <anonymous> (utils/native-wait.ts:102)
    at map (native)
    at <anonymous> (utils/native-wait.ts:102)
    at Promise (native)
    at forModule (utils/native-wait.ts:104)
    at initialize (il2cpp/module.ts:16)
    at perform (il2cpp/perform.ts:5)
    at <anonymous> (index.ts:17)
```

**Comment by colo13verdadeo** [comment]
Sometimes is translate to ARM, so, on this version IL cant doit and crash.

**Comment by Gouadala** [comment]
I do get that error too but the solution is simple.... When you get that error just wait for the game to load... And then just edit your frida script... What ido is  adding some comment then save it... If you use the build method... Run the build commend... If you use the watch method... It will rebuild the script and inject it back to the game ...

That would solve the probelm....


An other method  is to set a timeout function to wait for the game to be fully loaded before runnig the frida script (il2ccp part)

Good look!

**Comment by Sazxt** [comment]
solved, I use the old Frida ldplayer emulator version 15 and Frida tools version 10

**Comment by ghost** [comment]
> solved, I use the old Frida ldplayer emulator version 15 and Frida tools version 10

Can you send me the old versions?

**Comment by colo13verdadeo** [comment]
@Yehh22 Just use Emulator with ARM.

**Comment by ghost** [comment]
> @Yehh22 Just use Emulator with ARM.

What emulator?

**Comment by colo13verdadeo** [comment]
> > @Yehh22 Just use Emulator with ARM.
> 
> What emulator?

I've heard: Waydroid, try use.
Reply me if works or not works @Yehh22 .

**Comment by ghost** [comment]
> > > @Yehh22 Just use Emulator with ARM.
> > 
> > 
> > What emulator?
> 
> I've heard: Waydroid, try use. Reply me if works or not works @Yehh22 .

I don't use linux. Forget it, I use phone instead

**Comment by MadProgrammerGR** [comment]
I had the same problem and i fixed it by injecting the Frida Gadget using Python LIEF library instead: 
1. Extracted `split_config.armeabi_v7a.apk` (depends on your architecture) using apktool to find the `libil2cpp.so` library
2. Copied `libfrida-gadget.so` and `libfrida-gadget.config.so` next to it
3. Used LIEF to inject the Frida Gadget to `libil2cpp.so` (only few lines of python code)
4. Built with apktool & signapk with Objection

I _think_ the problem was that previously when i was using Objection's patchapk (equivalently `loadLibrary()` Smali/Java injection) Frida was being injected to a different process (from base.apk) that only spawned another process from split_config.apk hence it couldn't see it.
